// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WCFService;

namespace WCFService.Migrations
{
    [DbContext(typeof(WiFiNetworkContext))]
    partial class WiFiNetworkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WCFService.WiFiNetwork", b =>
                {
                    b.Property<string>("BSSID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(17);

                    b.Property<string>("Encryption")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<int>("Frequency");

                    b.Property<DateTime>("LastDetection");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<double>("RSSI");

                    b.Property<string>("SSID")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(true);

                    b.HasKey("BSSID");

                    b.ToTable("WiFiNetworks");
                });
#pragma warning restore 612, 618
        }
    }
}
